graph TD
    S([Start]) --> P1[Try Open 'products.txt' for Input]
    P1 --> D1{File Exists?}
    D1 -- Yes --> C1[Close Input File]
    C1 --> O1[/Display 'Generated Successfully'/]
    O1 --> E([Return])
    
    D1 -- No --> P2[Open 'products.txt' for Output]
    P2 --> W1[/Write Default Products 1-6/]
    W1 --> C2[Close Output File]
    C2 --> C1