graph TD
    S([Start]) --> C1[[Call loadProductsFromFile]]
    C1 --> C2[[Call welcome]]
    C2 --> C3[[Call login]]
    C3 --> D1{Login Success?}
    D1 -- False --> O1[/Display Goodbye/]
    O1 --> E([End])
    D1 -- True --> D2{Is Admin?}
    D2 -- Yes --> C4[[Call adminMenu]]
    D2 -- No --> C5[[Call customerMenu]]
    C4 & C5 --> I1[/Input 'Login Again?'/]
    I1 --> D3{Answer == 'N'?}
    D3 -- No --> C3
    D3 -- Yes --> O2[/Display Exiting/]
    O2 --> E